type:      map
mapping:
  "settings":
    type:      map
    mapping:
      "es_host":
        type: str
        required:  yes
      "es_port": 
        type: int
        required:  yes
  "probes":
    type:      seq
    sequence:
      - type:    map
        mapping:
          "time_aggregator":
            type:      str
            required:  yes
          "name":
            type:      str
            required:  yes
            unique:    yes
          "value_fields":
            type:      str
            required:  yes
          "time_window":
            type:      str
            required:  yes
          "std_multiply":
            type:      int
            required:  yes
          "times_to_run":
            type:      int
            required:  yes
          "must":
            type:      seq
            sequence:
              - type:    map
                mapping:
                  "key":
                    type:     str
                  "value":
                    type:     str
          "must_not":
            type:      seq
            sequence:
              - type:    map
                mapping:
                  "key":
                    type:     str
                  "value":
                    type:     str
          "should":
            type:      seq
            sequence:
              - type:    map
                mapping:
                  "key":
                    type:     str
                  "value":
                    type:     str

